name: flutter_camera_example
description: Example with Flutter camera
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.2
  camera: ^0.11.0
  path_provider: ^2.0.11
  path: ^1.8.0
  video_player: ^2.6.0
  video_thumbnail: ^0.5.3
  provider: ^6.0.5
  # ffmpeg_kit_flutter_full: ^5.1.0
  ffmpeg_kit_flutter_min_gpl: ^6.0.3

  url_launcher: ^6.1.10
  whatsapp_share: 2.0.2
  share_plus: 7.2.1
  image_picker: ^0.8.7+5
  flutter_colorpicker: ^1.0.3





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/templates/    
    - assets/audio/
    - assets/fonts/Roboto-Regular.ttf
    - assets/fonts/Rubik-Regular.ttf
